test/unit/src/org/kuali/kfs/module/external/kc/service/impl/WebServicesImplTest.java, work/src/org/kuali/kfs/module/external/kc/service/impl/AwardServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/AwardTypeServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/BillingFrequencyServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/BudgetCategoryServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/CfdaServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/LetterOfCreditFundGroupServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/LetterOfCreditFundServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/SponsorServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/service/impl/UnitServiceImpl.java, work/src/org/kuali/kfs/module/external/kc/spring-kc.xml, work/src/org/kuali/kfs/module/external/kc/webService/AwardAccountSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/AwardPaymentWebSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/AwardTypeWebSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/AwardWebSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/CfdaNumberSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/FrequencyWebSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/InstitutionalBudgetCategorySoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/InstitutionalUnitSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/KfsKcSoapService.java, work/src/org/kuali/kfs/module/external/kc/webService/SponsorWebSoapService.java
move KfsService to webServices package in kc integration module; rename to KfsKcSoapService; and fix remove references to that class in the external.kc.service package.
=> KFSTP-1656

work/src/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java
Account summary should include all balances, even if they do not have an associated category.
=> KFSTP-1664

work/src/org/kuali/kfs/module/external/kc/dto/DunningCampaignDTO.java
add serialVersionUID to DunningCampaignDTO
=> KFSTP-1657

work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsInvoiceDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/web/struts/ContractsGrantsInvoiceDocumentAction.java
Base Customer Invoice Detail / source accounting line totals off of invoice amounts in c&g invoice detail current expenditure amounts.  Also, recalcuate source accounting line totals when the document is pending after any action.
=> KFSTP-1688

work/src/org/kuali/kfs/module/ar/document/ContractsGrantsInvoiceDocument.java, work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsInvoiceDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
Add logic to force batch-created CINVs which would do not pass routing validation to route to funds manager.
=> KFSTP-1697

work/src/org/kuali/kfs/module/ar/document/ContractsGrantsInvoiceDocument.java, work/src/org/kuali/kfs/module/ar/document/CustomerInvoiceDocument.java
Break out logic of how customer invoices decide what is a debit for GLPE generation, so that CINV can override; CINV only cares whether an amount is positive or negative.
=> KFSTP-1699

work/src/org/kuali/kfs/module/cg/CGKeyConstants.java, work/src/org/kuali/kfs/module/cg/CGPropertyConstants.java, work/src/org/kuali/kfs/module/cg/cg-resources.properties, work/src/org/kuali/kfs/module/cg/document/validation/impl/AgencyRule.java
Add validation to agency that when existing customer option is chosen, that the customer number is filled in and refers to a valid, existing, active customer
=> KFSTP-1739

work/src/org/kuali/kfs/module/ar/businessobject/lookup/CollectionActivityInvoiceLookupableHelperServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/dataaccess/ContractsGrantsInvoiceDocumentDao.java, work/src/org/kuali/kfs/module/ar/document/dataaccess/impl/ContractsGrantsInvoiceDocumentDaoOjb.java, work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsCollectionActivityDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsInvoiceDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsCollectionActivityDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
Add logic to restrict which CINV documents the c&g collection activity document can lookup; also reorganize code a bit to make a bit more sense of what methods should be found where
=> KFSTP-1707

work/src/org/kuali/kfs/module/ar/document/InvoiceRecurrenceMaintainable.java
Clear out the customer invoice doc on the invoice recurrence right before it is linked and saved, so that the business object linking doesn't get all upset
=> KFSTP-1759

work/src/org/kuali/kfs/module/ar/document/InvoiceRecurrenceMaintainable.java
=> Revert "KFSTP-1759"

work/src/org/kuali/kfs/module/ar/businessobject/InvoiceRecurrence.java, work/src/org/kuali/kfs/module/ar/document/InvoiceRecurrenceMaintainable.java, work/src/org/kuali/kfs/module/ar/ojb-ar.xml
=> Revert "KFSTP-1759 Removing faulty reference-descriptor"

work/src/org/kuali/kfs/module/ar/ojb-ar.xml
add auto-increment to back lockbox table
=> KFSTP-1769

work/src/org/kuali/kfs/module/ar/document/ContractsGrantsLetterOfCreditReviewDocument.java, work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsLetterOfCreditReviewDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsLetterOfCreditReviewDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
Negate amount to draw from award account to determine claim on cash balance; remove all the other logic which was supposed to (but failed) calculating claim on cash balance
=> KFSTP-1548

work/db/upgrades/5.0.3_cgb/db/01_structure/ar-module-structure-updates.xml, work/src/org/kuali/kfs/module/ar/ojb-ar.xml
Rename database columns to better match the functional names of the fields
=> KFSTP-1801

work/src/org/kuali/kfs/module/ar/ArKeyConstants.java, work/src/org/kuali/kfs/module/ar/ar-resources.properties, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/validation/configuration/AccountsReceivableValidators.xml, work/src/org/kuali/kfs/module/ar/document/validation/configuration/ContractsGrantsInvoiceValidation.xml, work/src/org/kuali/kfs/module/ar/document/validation/impl/ContractsGrantsInvoiceDocumentInvoiceDetailAccountObjectCodeFinancialObjectCodesValidation.java, work/src/org/kuali/kfs/module/ar/service/CostCategoryService.java, work/src/org/kuali/kfs/module/ar/service/impl/CostCategoryServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
Add logic to choose a "random" object code within a category if invoice detail account object code cannot find one otherwise; validate that invoice detail account object codes have financial object code set prior to saving
=> KFSTP-1793

test/unit/src/org/kuali/kfs/module/ar/batch/service/ContractsGrantsInvoiceCreateDocumentServiceTest.java, test/unit/src/org/kuali/kfs/module/ar/batch/service/impl/ContractsGrantsInvoiceBatchCreateDocumentServiceTest.java, test/unit/src/org/kuali/kfs/module/ar/businessobject/lookup/ContractsGrantsAgingOpenInvoicesReportLookupableHelperServiceImplTest.java, test/unit/src/org/kuali/kfs/module/ar/businessobject/lookup/ContractsGrantsAgingReportLookupableHelperServiceImplTest.java, test/unit/src/org/kuali/kfs/module/ar/businessobject/lookup/DunningLetterDistributionLookupableHelperServiceImplTest.java, test/unit/src/org/kuali/kfs/module/ar/businessobject/lookup/TicklersReportLookupableHelperServiceImplTest.java, test/unit/src/org/kuali/kfs/module/ar/document/CGInvoiceDocumentTestBase.java, test/unit/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsAgingOpenInvoicesReportServiceTest.java, test/unit/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsAgingReportServiceTest.java, test/unit/src/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImplTest.java, work/src/org/kuali/kfs/module/ar/businessobject/datadictionary/ContractsGrantsLetterOfCreditReviewDetail.xml, work/src/org/kuali/kfs/module/ar/document/ContractsGrantsLetterOfCreditReviewDocument.java, work/src/org/kuali/kfs/module/ar/document/service/ContractsGrantsLetterOfCreditReviewDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsLetterOfCreditReviewDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/service/ContractsGrantsInvoiceCreateDocumentService.java, work/src/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml, work/src/org/kuali/kfs/module/cg/businessobject/AwardAccount.java, work/web-root/WEB-INF/tags/module/ar/contractsGrantsLetterOfCreditReviewDetail.tag
Implement take a penny, leave a penny for category redistributions on CINVs created via LOC Review.  Oh, and hey, while we're at it, let's correct all of that logic and make major changes to the CINV generation code
=> KFSTP-1784

work/src/org/kuali/kfs/module/ar/document/service/impl/CustomerAddressServiceImpl.java
be more careful about retrieving primary address - there may not be one...
=> KFSTP-1799

work/src/org/kuali/kfs/module/ar/document/web/struts/ContractsGrantsLetterOfCreditReviewDocumentAction.java
Allow export and generate report on LOC Review doc to work with either fund group or just fund; also remove no longer needed logic
=> KFSTP-1824

work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java
Be smarter about checking billing frequency before finding the accounting line amount for a c&g invoice
=> KFSTP-1829

work/src/org/kuali/kfs/module/ar/document/authorization/ContractsGrantsInvoiceDocumentPresentationController.java
Do not allow edits on CINVs created via LOC
=> KFSTP-1848

work/src/org/kuali/kfs/module/ar/ArPropertyConstants.java, work/src/org/kuali/kfs/module/ar/businessobject/lookup/ContractsGrantsPaymentHistoryReportLookupableHelperServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml, work/src/org/kuali/kfs/sys/KFSPropertyConstants.java
rewrite c&g payment history report to query against invoice payment applied records
=> KFSTP-1853

work/src/org/kuali/kfs/module/ar/document/PaymentApplicationDocument.java
Always pull back object code, even if refresh fails to do so
=> KFSTP-1861

work/src/org/kuali/kfs/module/cg/batch/MoveAgencyAndAwardMaintDocNotesToBusinessObjectsStep.java, work/src/org/kuali/kfs/module/cg/batch/service/MaintenanceDocumentNotesMigrationService.java, work/src/org/kuali/kfs/module/cg/batch/service/impl/MaintenanceDocumentNotesMigrationServiceImpl.java, work/src/org/kuali/kfs/module/cg/spring-cg.xml
Create batch job to convert agency and award maintenance document notes to BO notes
=> KFSTI-1245

work/db/upgrades/5.0.3_cgb/rice_server/kim_upgrade.xml
=> KFSTI-1272

work/src/org/kuali/kfs/module/cg/web/struts/ContractsGrantsAwardBalancesReportLookupForm.java
Add displayActionsForRow property to form, so jsp will be happy
=> KFSTP-1897

work/src/org/kuali/kfs/module/ar/businessobject/lookup/ContractsGrantsInvoiceReportLookupableHelperServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/service/CustomerInvoiceDocumentService.java, work/src/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/document/service/impl/CustomerInvoiceDocumentServiceImpl.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
Limit invoice paid applieds used by award balances report to those that come from payment applications or customer credit memos
=> KFSTP-1905

work/src/org/kuali/kfs/module/ar/batch/ClearContractsGrantsInvoiceDocumentErrorLogStep.java, work/src/org/kuali/kfs/module/ar/batch/ContractsGrantsInvoiceDocumentBatchStep.java, work/src/org/kuali/kfs/module/ar/batch/ContractsGrantsInvoiceRouteDocumentsStep.java, work/src/org/kuali/kfs/module/ar/batch/LetterOfCreditCreateAndRouteDocumentsStep.java, work/src/org/kuali/kfs/module/ar/batch/UpcomingMilestoneNotificationStep.java, work/src/org/kuali/kfs/module/ar/spring-ar.xml
If CGB is turned off, then do not run batch jobs associated with CGB; log about it instead
=> KFSTP-1916

work/db/upgrades/5.4.1_6.0/db/01_structure/endow-module-structure-updates.xml
Corrections to the script - delete views correctly; delete tables which were not in ojb; make sure we kill all foreign keys before killing any tables
=> KFSTP-1932

src/main/java/org/kuali/kfs/sys/context/PropertyLoadingFactoryBean.java, src/main/resources/OJB-logging.properties, src/main/resources/OJB-repository.xml, src/main/resources/OJB.properties, src/main/resources/kfs-default-config.properties, src/main/resources/kfs-rice-default-config.properties
We may have to adjust the property resolution or maybe modify PropertyLoadingFactoryBean to do the resolution.
=> KFSTP-1927 Creating kfs and rice defaults files

.gitignore, pom.xml, src/main/resources/log4j.properties
First step in making it able to run Tomcat via Maven; only works with mysql though
=> KFSTP-1951

pom.xml
=> Revert "general pom cleanup, dependency tree pruning"

pom.xml
Jeff's latest changes to the pom.xml
=> jcaddel-KFSTP-1947

src/main/config/scripts/maven_mover.rb
Move maven_mover.rb to new home; make sure it would still work in new home; add note to remind us to throw this away some day
=> KFSTI-1683

ivy.xml
=> KFSTP-1968

pom.xml
Update version of wss4j in use
=> KFSTP-1969

src/main/java/org/kuali/kfs/sys/context/PropertyLoadingFactoryBean.java
The sysout is a temp thing so I don't have to fight log4j too much yet.
=> KFSTI-1371 Add logging to PropertyLoadingFactoryBean

.gitignore
gitignore netbeans, sublime text, and text mate
=> KFSTI-1747

src/main/config/work/staging/sys/batchContainer/placeholder.txt
Move work directory structure for now
=> KFSTI-1754

work/db/upgrades/5.4.1_6.0/rice_server/kew_upgrade.xml
Liquibase to completely remove all endowment document types.
=> KFSTI-1770

src/main/config/demo/procurementCard/procurementCard.readme
=> KFSTI-1773

pom.xml
working tests can be removed from pom's list of test exclusions
=> KFSTI-1780

src/main/java/org/kuali/kfs/module/tem/TemKeyConstants.java, src/main/resources/kfs-default-config.properties, src/main/webapp/WEB-INF/tags/portal/channel/main/transactions.tag, src/test/resources/test-configuration.properties
change the name of the property which allows travel reimbursements to be initiated without an authorization
=> KFSTP-1983

pom.xml
=> KFSTI-1850

src/test/java/org/kuali/kfs/sys/context/DocumentSerializabilityTest.java
Better logging, so we can see which document type entries were actually checked
=> KFSTI-1881

src/main/resources/org/kuali/kfs/fp/spring-fp.xml, src/main/resources/org/kuali/kfs/gl/spring-gl.xml, src/main/resources/org/kuali/kfs/module/ar/spring-ar.xml, src/main/resources/org/kuali/kfs/module/cam/spring-cam.xml, src/main/resources/org/kuali/kfs/module/ld/spring-ld.xml, src/main/resources/org/kuali/kfs/module/purap/spring-purap.xml, src/main/resources/org/kuali/kfs/module/tem/spring-tem.xml, src/main/resources/org/kuali/kfs/pdp/spring-pdp.xml, src/main/resources/org/kuali/kfs/vnd/spring-vnd.xml
Explicitly list all staging directories so that startup will automatically create them
=> KFSTP-1998

pom.xml
Create code and source jar and have those installed by Maven
=> KFSTI-1896

pom.xml, src/main/webapp/WEB-INF/tags/gl/generalLedgerPendingEntries.tag, src/main/webapp/WEB-INF/tags/module/ar/paymentApplicationControlInformation.tag, src/main/webapp/WEB-INF/tags/module/bc/appointmentFundingLineForPosition.tag, src/main/webapp/WEB-INF/tags/module/tem/travelPaymentPDPStatus.tag
Fix tags which Tomcat 7 didn't want to compile because of either use of java keywords in EL expressions or because of whitespace rules.
=> KFSTP-2006

kfs-core/src/main/config/kfs-skel-config.properties, kfs-core/src/main/java/org/kuali/kfs/sys/context/KFSConfigurer.java, kfs-core/src/main/resources/kfs-default-config.properties
Remove property from properties file. Override getRunMode method to always return RunMode.LOCAL.
=> KFSTI-2042

kfs-core/src/main/java/org/kuali/rice/krad/datadictionary/DataDictionary.java
Get resource names from URLs, which we're hoping will be more consistent.
=> KFSTI-2026

kfs-core/src/main/java/org/kuali/kfs/sys/service/ReportGenerationService.java, kfs-core/src/main/java/org/kuali/kfs/sys/service/impl/ReportGenerationServiceImpl.java, kfs-core/src/test/java/org/kuali/kfs/sys/service/ReportGenerationServiceTest.java, kfs-web/src/main/webapp/WEB-INF/tags/module/bc/pbglLineDataCellDetail.tag
Change report service to write to intermediate byte stream instead of dumping everything out to a file
=> KFSTP-2057

kfs-ar/src/main/java/org/kuali/kfs/module/ar/batch/service/impl/VerifyBillingFrequencyServiceImpl.java, kfs-ar/src/main/resources/org/kuali/kfs/module/ar/spring-ar.xml, kfs-ar/src/test/java/org/kuali/kfs/module/ar/document/service/VerifyBillingFrequencyServiceTest.java
Fixing a unit test for training
=> KFSTI-2080

README.md, kfs-cam/pom.xml, kfs-cg/pom.xml, kfs-core/pom.xml
=> KFSTI-1690

kfs-core/src/main/java/org/kuali/kfs/sys/service/impl/ReportGenerationServiceImpl.java
We need to write subreports to some directory, so let's just use temp!
=> KFSTI-2081

kfs-ar/src/main/java/org/kuali/kfs/module/ar/businessobject/BillingPeriod.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/businessobject/BillingPeriodTest.java
Merge in the testing and refactoring changes performed during training.
=> KFSTI-2080.1

kfs-ar/src/main/java/org/kuali/kfs/module/ar/batch/service/impl/LockboxServiceImpl.java, kfs-ar/src/main/resources/org/kuali/kfs/module/ar/spring-ar.xml
=> Revert "KFSTI-2080.1"

kfs-ar/src/main/java/org/kuali/kfs/module/ar/batch/service/VerifyBillingFrequencyService.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/batch/service/impl/VerifyBillingFrequencyServiceImpl.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/businessobject/BillingPeriod.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/businessobject/LetterOfCreditBillingPeriod.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriod.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsBillingAwardVerificationServiceImpl.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/businessobject/BillingPeriodTest.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/businessobject/LetterOfCreditBillingPeriodTest.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriodTest.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/document/service/VerifyBillingFrequencyServiceTest.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/service/ContractsGrantsInvoiceCreateTestBase.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImplTest.java
Using refactoring to clarify the logic of when an Award may next be billed by a CINV doc
=> KFSTI-2079

kfs-ar/src/main/java/org/kuali/kfs/module/ar/document/authorization/ContractsGrantsInvoiceDocumentPresentationController.java, kfs-ar/src/test/java/org/kuali/kfs/module/ar/document/authorization/ContractsGrantsInvoiceDocumentPresentationControllerTest.java
cleaned up code and tests and fixed bug
=> KFSTP-2066

kfs-ar/src/main/java/org/kuali/kfs/module/ar/document/ContractsGrantsInvoiceDocument.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/document/validation/impl/InvoiceAmountLessThanInvoiceMinimumSuspensionCategory.java, kfs-ar/src/main/java/org/kuali/kfs/module/ar/document/web/struts/ContractsGrantsInvoiceDocumentAction.java, kfs-ar/src/main/resources/org/kuali/kfs/module/ar/spring-ar.xml
fix bugs: 
- invoice amount may not be current when suspension category checked
- OJB Optimistic Lock Exception - suspension category not deleted when removed from CINV doc
=> KFSTP-2075

kfs-ar/src/main/java/org/kuali/kfs/module/ar/businessobject/defaultvalue/DefaultInvoiceTemplateFinder.java, kfs-bc/src/main/java/org/kuali/kfs/module/bc/businessobject/CalculatedSalaryFoundationTracker.java, kfs-bc/src/main/java/org/kuali/kfs/module/bc/service/impl/HumanResourcesPayrollServiceImpl.java, kfs-cam/src/main/java/org/kuali/kfs/module/cab/dataaccess/impl/ReconciliationDaoOjb.java, kfs-core/src/main/java/org/kuali/kfs/vnd/businessobject/lookup/DebarredVendorUnmatchedLookupableHelperServiceImpl.java, kfs-ld/src/main/java/org/kuali/kfs/module/ld/businessobject/AccountStatusCurrentFunds.java, kfs-ld/src/main/java/org/kuali/kfs/module/ld/businessobject/July1PositionFunding.java, kfs-ld/src/main/java/org/kuali/kfs/module/ld/businessobject/LaborCalculatedSalaryFoundationTracker.java, kfs-tem/src/main/java/org/kuali/kfs/module/tem/businessobject/lookup/TemProfileAddressLookupableHelperServiceImpl.java
replace org.apache.cxf.common.util.StringUtils with org.apache.commons.lang.StringUtils.
=> KFSTP-2099

kfs-core/src/test/java/org/kuali/kfs/sys/document/validation/MaintenanceRuleTestBase.java
remove groovy logger import and other unused imports
=> KFSTP-2100

kfs-tem/src/main/java/org/kuali/kfs/module/tem/document/service/impl/TemCorrectionDocumentServiceImpl.java
remove references to dom4j in the project
=> KFSTP-2101

kfs-purap/src/main/java/org/kuali/kfs/module/purap/document/PurchaseOrderDocument.java, kfs-purap/src/test/java/org/kuali/kfs/module/purap/document/PurchaseOrderDocumentTest.java
Fix issue with negative value on the PO with trade in.
=> KFSTP-2111

kfs-purap/src/main/java/org/kuali/kfs/module/purap/document/web/struts/AccountsPayableActionBase.java
Save only the note on the POC close, so that GLPEs are not potentially lost.
=> KFSTP-2114
